import { Router } from "express";
import crypto from "crypto";
import { royaltyStamp } from "../lib/royalty.js";

const router = Router();

// ============================================================
// Phantom Capital Cryptography Services
// All encryption, signing, hashing, and key management
// services are covered under Phantom Capital Royalty License v1.0
// Royalty: 5% of crypto-service-related revenue for derivatives
// ============================================================

// POST /crypto/keypair — Generate any type of keypair
router.post("/crypto/keypair", (req, res) => {
  try {
    const { algorithm, agentName, walletAddress } = req.body;
    const algo = (algorithm || "ed25519").toLowerCase();

    let publicKey, privateKey, pubHex, privHex, keyType;

    if (algo === "ed25519") {
      const pair = crypto.generateKeyPairSync("ed25519");
      pubHex = pair.publicKey.export({ type: "spki", format: "der" }).toString("hex");
      privHex = pair.privateKey.export({ type: "pkcs8", format: "der" }).toString("hex");
      keyType = "Ed25519";
    } else if (algo === "rsa" || algo === "rsa-4096") {
      const pair = crypto.generateKeyPairSync("rsa", {
        modulusLength: 4096,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });
      pubHex = Buffer.from(pair.publicKey).toString("base64");
      privHex = Buffer.from(pair.privateKey).toString("base64");
      keyType = "RSA-4096";
    } else if (algo === "rsa-2048") {
      const pair = crypto.generateKeyPairSync("rsa", {
        modulusLength: 2048,
        publicKeyEncoding: { type: "spki", format: "pem" },
        privateKeyEncoding: { type: "pkcs8", format: "pem" },
      });
      pubHex = Buffer.from(pair.publicKey).toString("base64");
      privHex = Buffer.from(pair.privateKey).toString("base64");
      keyType = "RSA-2048";
    } else if (algo === "x25519") {
      const pair = crypto.generateKeyPairSync("x25519");
      pubHex = pair.publicKey.export({ type: "spki", format: "der" }).toString("hex");
      privHex = pair.privateKey.export({ type: "pkcs8", format: "der" }).toString("hex");
      keyType = "X25519 (Diffie-Hellman)";
    } else if (algo === "ec" || algo === "ecdsa") {
      const pair = crypto.generateKeyPairSync("ec", { namedCurve: "prime256v1" });
      pubHex = pair.publicKey.export({ type: "spki", format: "der" }).toString("hex");
      privHex = pair.privateKey.export({ type: "pkcs8", format: "der" }).toString("hex");
      keyType = "ECDSA (P-256)";
    } else {
      return res.status(400).json({
        error: "Unsupported algorithm",
        supported: ["ed25519", "rsa-2048", "rsa-4096", "x25519", "ec"],
      });
    }

    const fingerprint = crypto.createHash("sha256").update(pubHex).digest("hex").slice(0, 16);
    const createdAt = new Date().toISOString();

    return res.status(201).json({
      ok: true,
      keypair: {
        algorithm: keyType,
        publicKey: pubHex,
        privateKey: privHex,
        fingerprint,
        createdAt,
        agentName: agentName || null,
        walletAddress: walletAddress || null,
      },
      soulMdBlock: [
        `## Cryptographic Identity (${keyType})`,
        "",
        `- **Agent:** ${agentName || "unnamed"}`,
        `- **Public Key:** ${pubHex.slice(0, 80)}${pubHex.length > 80 ? "..." : ""}`,
        `- **Fingerprint:** ${fingerprint}`,
        `- **Algorithm:** ${keyType}`,
        `- **Created:** ${createdAt}`,
        walletAddress ? `- **Wallet:** ${walletAddress}` : null,
        "",
        "Generated by Phantom Capital Cryptography Services",
        "https://phantomskills.zeabur.app",
      ].filter(Boolean).join("\n"),
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("keypair error:", err);
    return res.status(500).json({ error: "Key generation failed" });
  }
});

// POST /crypto/encrypt — AES-256-GCM encryption
router.post("/crypto/encrypt", (req, res) => {
  try {
    const { plaintext, key } = req.body;
    if (!plaintext) return res.status(400).json({ error: "plaintext required" });

    // Generate or use provided key
    const aesKey = key
      ? Buffer.from(key, "hex")
      : crypto.randomBytes(32);
    const iv = crypto.randomBytes(12);

    const cipher = crypto.createCipheriv("aes-256-gcm", aesKey, iv);
    let encrypted = cipher.update(plaintext, "utf8", "hex");
    encrypted += cipher.final("hex");
    const authTag = cipher.getAuthTag().toString("hex");

    return res.json({
      ok: true,
      ciphertext: encrypted,
      iv: iv.toString("hex"),
      authTag,
      algorithm: "AES-256-GCM",
      key: key ? undefined : aesKey.toString("hex"),
      note: key ? undefined : "New key generated — store it securely. Shown ONCE.",
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("encrypt error:", err);
    return res.status(500).json({ error: "Encryption failed" });
  }
});

// POST /crypto/decrypt — AES-256-GCM decryption
router.post("/crypto/decrypt", (req, res) => {
  try {
    const { ciphertext, key, iv, authTag } = req.body;
    if (!ciphertext || !key || !iv || !authTag) {
      return res.status(400).json({ error: "ciphertext, key, iv, and authTag required" });
    }

    const decipher = crypto.createDecipheriv(
      "aes-256-gcm",
      Buffer.from(key, "hex"),
      Buffer.from(iv, "hex")
    );
    decipher.setAuthTag(Buffer.from(authTag, "hex"));
    let decrypted = decipher.update(ciphertext, "hex", "utf8");
    decrypted += decipher.final("utf8");

    return res.json({ ok: true, plaintext: decrypted });
  } catch (err) {
    return res.status(400).json({ error: "Decryption failed — wrong key or tampered data" });
  }
});

// POST /crypto/hash — Hash data with any algorithm
router.post("/crypto/hash", (req, res) => {
  try {
    const { data, algorithm } = req.body;
    if (!data) return res.status(400).json({ error: "data required" });

    const algo = (algorithm || "sha256").toLowerCase();
    const supported = ["sha256", "sha512", "sha3-256", "sha3-512", "blake2b512", "md5"];

    if (!supported.includes(algo)) {
      return res.status(400).json({ error: "Unsupported algorithm", supported });
    }

    const hash = crypto.createHash(algo).update(data).digest("hex");

    return res.json({
      ok: true,
      hash,
      algorithm: algo,
      inputLength: data.length,
    });
  } catch (err) {
    console.error("hash error:", err);
    return res.status(500).json({ error: "Hashing failed" });
  }
});

// POST /crypto/hmac — HMAC signing
router.post("/crypto/hmac", (req, res) => {
  try {
    const { data, key, algorithm } = req.body;
    if (!data) return res.status(400).json({ error: "data required" });

    const algo = (algorithm || "sha256").toLowerCase();
    const hmacKey = key || crypto.randomBytes(32).toString("hex");
    const hmac = crypto.createHmac(algo, Buffer.from(hmacKey, "hex")).update(data).digest("hex");

    return res.json({
      ok: true,
      hmac,
      algorithm: algo,
      key: key ? undefined : hmacKey,
      note: key ? undefined : "New key generated — store it securely.",
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("hmac error:", err);
    return res.status(500).json({ error: "HMAC failed" });
  }
});

// POST /crypto/hmac/verify — Verify HMAC
router.post("/crypto/hmac/verify", (req, res) => {
  try {
    const { data, key, hmac, algorithm } = req.body;
    if (!data || !key || !hmac) {
      return res.status(400).json({ error: "data, key, and hmac required" });
    }

    const algo = (algorithm || "sha256").toLowerCase();
    const expected = crypto.createHmac(algo, Buffer.from(key, "hex")).update(data).digest("hex");
    const valid = crypto.timingSafeEqual(Buffer.from(hmac, "hex"), Buffer.from(expected, "hex"));

    return res.json({ ok: true, valid });
  } catch (err) {
    return res.status(400).json({ error: "HMAC verification failed" });
  }
});

// POST /crypto/rsa/encrypt — RSA public key encryption (PGP-style)
router.post("/crypto/rsa/encrypt", (req, res) => {
  try {
    const { plaintext, publicKey } = req.body;
    if (!plaintext || !publicKey) {
      return res.status(400).json({ error: "plaintext and publicKey required" });
    }

    const pubKeyPem = Buffer.from(publicKey, "base64").toString("utf8");
    const encrypted = crypto.publicEncrypt(
      { key: pubKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: "sha256" },
      Buffer.from(plaintext)
    ).toString("base64");

    return res.json({
      ok: true,
      ciphertext: encrypted,
      algorithm: "RSA-OAEP-SHA256",
      note: "Decrypt with the corresponding private key",
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("rsa encrypt error:", err);
    return res.status(500).json({ error: "RSA encryption failed" });
  }
});

// POST /crypto/rsa/decrypt — RSA private key decryption
router.post("/crypto/rsa/decrypt", (req, res) => {
  try {
    const { ciphertext, privateKey } = req.body;
    if (!ciphertext || !privateKey) {
      return res.status(400).json({ error: "ciphertext and privateKey required" });
    }

    const privKeyPem = Buffer.from(privateKey, "base64").toString("utf8");
    const decrypted = crypto.privateDecrypt(
      { key: privKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: "sha256" },
      Buffer.from(ciphertext, "base64")
    ).toString("utf8");

    return res.json({ ok: true, plaintext: decrypted });
  } catch (err) {
    return res.status(400).json({ error: "RSA decryption failed — wrong key or corrupted data" });
  }
});

// POST /crypto/rsa/sign — RSA digital signature
router.post("/crypto/rsa/sign", (req, res) => {
  try {
    const { message, privateKey } = req.body;
    if (!message || !privateKey) {
      return res.status(400).json({ error: "message and privateKey required" });
    }

    const privKeyPem = Buffer.from(privateKey, "base64").toString("utf8");
    const timestamp = new Date().toISOString();
    const payload = `${message}|${timestamp}`;

    const signature = crypto.sign("sha256", Buffer.from(payload), privKeyPem).toString("base64");

    return res.json({
      ok: true,
      payload,
      signature,
      timestamp,
      algorithm: "RSA-SHA256",
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("rsa sign error:", err);
    return res.status(500).json({ error: "RSA signing failed" });
  }
});

// POST /crypto/rsa/verify — Verify RSA signature
router.post("/crypto/rsa/verify", (req, res) => {
  try {
    const { payload, signature, publicKey } = req.body;
    if (!payload || !signature || !publicKey) {
      return res.status(400).json({ error: "payload, signature, and publicKey required" });
    }

    const pubKeyPem = Buffer.from(publicKey, "base64").toString("utf8");
    const valid = crypto.verify("sha256", Buffer.from(payload), pubKeyPem, Buffer.from(signature, "base64"));

    return res.json({ ok: true, valid });
  } catch (err) {
    return res.status(400).json({ error: "RSA verification failed" });
  }
});

// POST /crypto/random — Generate cryptographically secure random bytes
router.post("/crypto/random", (req, res) => {
  try {
    const { bytes, encoding } = req.body;
    const numBytes = Math.min(Number(bytes) || 32, 1024);
    const enc = encoding || "hex";

    const random = crypto.randomBytes(numBytes).toString(enc);

    return res.json({
      ok: true,
      random,
      bytes: numBytes,
      encoding: enc,
    });
  } catch (err) {
    return res.status(500).json({ error: "Random generation failed" });
  }
});

// POST /crypto/pgp/envelope — PGP-style hybrid encryption
// Encrypts data with AES, then encrypts the AES key with recipient's RSA public key
router.post("/crypto/pgp/envelope", (req, res) => {
  try {
    const { plaintext, recipientPublicKey } = req.body;
    if (!plaintext || !recipientPublicKey) {
      return res.status(400).json({ error: "plaintext and recipientPublicKey required" });
    }

    // Generate random AES key
    const aesKey = crypto.randomBytes(32);
    const iv = crypto.randomBytes(12);

    // Encrypt data with AES
    const cipher = crypto.createCipheriv("aes-256-gcm", aesKey, iv);
    let ciphertext = cipher.update(plaintext, "utf8", "hex");
    ciphertext += cipher.final("hex");
    const authTag = cipher.getAuthTag().toString("hex");

    // Encrypt AES key with recipient's RSA public key
    const pubKeyPem = Buffer.from(recipientPublicKey, "base64").toString("utf8");
    const encryptedKey = crypto.publicEncrypt(
      { key: pubKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: "sha256" },
      aesKey
    ).toString("base64");

    return res.json({
      ok: true,
      envelope: {
        encryptedKey,
        ciphertext,
        iv: iv.toString("hex"),
        authTag,
        algorithm: "PGP-style: RSA-OAEP-SHA256 + AES-256-GCM",
      },
      instructions: "Send the entire envelope to the recipient. They decrypt encryptedKey with their RSA private key, then use it to decrypt ciphertext.",
      ...royaltyStamp(),
    });
  } catch (err) {
    console.error("pgp envelope error:", err);
    return res.status(500).json({ error: "PGP envelope encryption failed" });
  }
});

// POST /crypto/pgp/open — Open a PGP-style envelope
router.post("/crypto/pgp/open", (req, res) => {
  try {
    const { envelope, privateKey } = req.body;
    if (!envelope || !privateKey) {
      return res.status(400).json({ error: "envelope and privateKey required" });
    }

    const { encryptedKey, ciphertext, iv, authTag } = envelope;

    // Decrypt AES key with RSA private key
    const privKeyPem = Buffer.from(privateKey, "base64").toString("utf8");
    const aesKey = crypto.privateDecrypt(
      { key: privKeyPem, padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: "sha256" },
      Buffer.from(encryptedKey, "base64")
    );

    // Decrypt data with AES key
    const decipher = crypto.createDecipheriv("aes-256-gcm", aesKey, Buffer.from(iv, "hex"));
    decipher.setAuthTag(Buffer.from(authTag, "hex"));
    let plaintext = decipher.update(ciphertext, "hex", "utf8");
    plaintext += decipher.final("utf8");

    return res.json({ ok: true, plaintext });
  } catch (err) {
    return res.status(400).json({ error: "Failed to open envelope — wrong key or tampered data" });
  }
});

// GET /crypto/algorithms — List all available services
router.get("/crypto/algorithms", (_req, res) => {
  return res.json({
    services: {
      keypairs: {
        endpoint: "POST /crypto/keypair",
        algorithms: ["ed25519", "rsa-2048", "rsa-4096", "x25519", "ec (ECDSA P-256)"],
        description: "Generate cryptographic keypairs for identity, signing, or encryption",
      },
      symmetricEncryption: {
        encrypt: "POST /crypto/encrypt",
        decrypt: "POST /crypto/decrypt",
        algorithm: "AES-256-GCM (authenticated encryption)",
        description: "Encrypt/decrypt data with a shared key",
      },
      hashing: {
        endpoint: "POST /crypto/hash",
        algorithms: ["sha256", "sha512", "sha3-256", "sha3-512", "blake2b512", "md5"],
        description: "One-way hash of data",
      },
      hmac: {
        sign: "POST /crypto/hmac",
        verify: "POST /crypto/hmac/verify",
        algorithms: ["sha256", "sha512"],
        description: "Keyed hash for message authentication",
      },
      rsaEncryption: {
        encrypt: "POST /crypto/rsa/encrypt",
        decrypt: "POST /crypto/rsa/decrypt",
        algorithm: "RSA-OAEP-SHA256",
        description: "Asymmetric encryption with RSA public/private keys",
      },
      rsaSignatures: {
        sign: "POST /crypto/rsa/sign",
        verify: "POST /crypto/rsa/verify",
        algorithm: "RSA-SHA256",
        description: "Digital signatures with RSA keys",
      },
      pgpEnvelope: {
        encrypt: "POST /crypto/pgp/envelope",
        decrypt: "POST /crypto/pgp/open",
        algorithm: "RSA-OAEP-SHA256 + AES-256-GCM (hybrid)",
        description: "PGP-style hybrid encryption — encrypt large data for a specific recipient",
      },
      random: {
        endpoint: "POST /crypto/random",
        description: "Cryptographically secure random bytes",
      },
      identity: {
        generate: "POST /identity/generate",
        sign: "POST /identity/sign",
        verify: "POST /identity/verify",
        description: "Ed25519 agent identity with SOUL.md integration",
      },
    },
    license: "Phantom Capital Royalty License v1.0",
    royalty: "5% of crypto-service-related revenue for derivative works",
    ...royaltyStamp(),
  });
});

export default router;
